name: Deploy Starlight Site

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Astro requires Node.js >=18.14.1

      # Step 3: Install dependencies in the "site/" folder
      - name: Install dependencies
        run: npm install
        working-directory: site

      # Step 4: Build the Astro project in the "site/" folder
      - name: Build the project
        run: npm run build
        working-directory: site

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/dist # Adjust if the output folder is different
