name: Deploy Starlight Site

on:
  push:
    branches:
      - main
      
   workflow_dispatch: # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Change to the "site/" directory
      - name: Navigate to site folder
        working-directory: site
        run: |
          echo "Working directory: $(pwd)"

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: site
        run: npm install

      # Step 5: Build the project
      - name: Build the project
        working-directory: site
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/dist
